POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hZ3V5IiwiZXhwIjoxNzYzMDc3NjYzLCJ1c2VySUQiOjIxfQ.zVBFZYhJol8bl8Mw8298-pca6SMN9Dk-DIAELUI1IZQ

{
    "name": "Test Event222",
    "description": "WTxF",
    "location": "tobleronixstan",
    "dateTime": "2023-10-12T15:30:12.00Z",
    "user_id": 1
}
